zuul:
  ignoredServices: '*'
  host:
    connect-timeout-millis: 20000
    socket-timeout-millis: 20000

  routes:
    listing-service:
        path: /listings/**
        serviceId: listing-service
        stripPrefix: false
        sensitiveHeaders:

server:
  port: 4000